sudo: false
dist: trusty
cache: pip
language: python
python:
  - "3.6"
install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pip install pipenv"
  - "pipenv install"

script:
  - "pipenv run pytest -v"